swagger: "2.0"
info:
  description: "This is a sample image classification server."
  version: "1.0.0"
  title: "Image Classification"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "luopengllpp@hotmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"


schemes:
- "https"
- "http"

paths:
  /predict:
    post:
      tags:
      - "image"
      summary: "predict a image "
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "image that needs to be predicted"
        required: true
        schema:
          type: "object"
      responses:
        "400":
          description: "Bad Request"
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/result"

  /history:
    get:
      tags:
      - "image"
      summary: "Returns all prediction result"
      description: "Returns all prediction result"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/result_with_id"


definitions:
  result_with_id:
    type: "object"
    required:
    - "image_url"
    - "prediction_result"
    properties:
      _id:
        type: "object"
        properties:
          Oid:
            type: "string"
            example: "5f2612b8bfe3763181e4e3d9"
      image_url:
        type: "string"
        example: "20200802091119124Cat_07464.jpg"
      prediction_result:
        type: "string"
        example: "[('n02123159', 'tiger_cat', 0.37779337), ('n02127052', 'lynx', 0.33435658), ('n02123045', 'tabby', 0.08329431), ('n02123394', 'Persian_cat', 0.02986822), ('n02129165', 'lion', 0.0023677386)]"


  result:
    type: "object"
    required:
    - "image_url"
    - "prediction_result"
    properties:
      image_url:
        type: "string"
        example: "20200802091119124Cat_07464.jpg"
      prediction_result:
        type: "string"
        example: "[('n02123159', 'tiger_cat', 0.37779337), ('n02127052', 'lynx', 0.33435658), ('n02123045', 'tabby', 0.08329431), ('n02123394', 'Persian_cat', 0.02986822), ('n02129165', 'lion', 0.0023677386)]"


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"